--- #YAML:1.0
name:               Video-CPL
version:            0.09
abstract:           Create and manipulate Coincident TV Programming Language (CPL) files.
author:
    - Carl Rosenberg <carl@coincident.tv>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:   0
    XML::Simple:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
